# Updates website for a release
name: "Update website"

on: 
  workflow_dispatch:
    inputs:
      input1:
        description: "Input #1"
        required: true
        default: "do we need inputs?"
      tag:
        description: "Release tag name"

jobs:
  website:
    name: "Update the website based on a release"
    runs-on: ubuntu-latest
    steps:
      #- uses: actions/checkout@v2
      #  with:
      #    fetch-depth: 0
      - name: "Echo something..."
        run: echo "This is something..."
